StajBul.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using StajBul.Entity;
using StajBul.Service;
using StajBul.WebUI.Models;

namespace StajBul.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IAnnouncementService announcementService;
        public HomeController(IAnnouncementService announcementService)
        {
            this.announcementService = announcementService;
        }
        public IActionResult Index(bool? isIntern, int? categoryId, string? searchedWords, int page = 1)
        {
            if (page <= 0)
            {
                page = 1;
            }

            CategoryFilterModel categoryFilterModel = new CategoryFilterModel(categoryId,isIntern,searchedWords);
            PaginationModel paginationModel = new PaginationModel();
            paginationModel.CurrentPage = page;
            paginationModel.PageSize = 9;
            categoryFilterModel.PaginationModel = paginationModel;
            ViewBag.categoryFilterModel = categoryFilterModel;
            return View();
        }

        public IActionResult Details(int id)
        {
            InternshipAnnouncement announcement = announcementService.getById(id);
            return View(announcement);
        }

        public IActionResult About()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddDays(1) }
            );

            return StatusCode(200);
        }
    }
}

StajBul.WebUI/ViewComponents/AnnouncementListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StajBul.Service;
using StajBul.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StajBul.WebUI.ViewComponents
{
    public class AnnouncementListViewComponent : ViewComponent
    {
        private IAnnouncementService announcementService;
        public AnnouncementListViewComponent(IAnnouncementService announcementService)
        {
            this.announcementService = announcementService;
        }
        public IViewComponentResult Invoke(CategoryFilterModel categoryFilterModel)
        {
            AnnouncementListAndPaginationModel announcementListAndPaginationModel = new AnnouncementListAndPaginationModel();
            string searchedWords = categoryFilterModel.SearchedWords?.ToLower();
            if (categoryFilterModel.CategoryId == null)
            {
                var query = (categoryFilterModel.IsIntern == true) ? announcementService.getAllStajyerAnnouncement() : announcementService.getAllCompanyAnnouncement();
                if(!string.IsNullOrEmpty(searchedWords))
                {
                    query = query.Where(a => a.Explanation.ToLower().Contains(searchedWords) || a.Title.ToLower().Contains(searchedWords) || a.Name.ToLower().Contains(searchedWords));
                }
                announcementListAndPaginationModel.PaginationModel = categoryFilterModel.PaginationModel;
                announcementListAndPaginationModel.PaginationModel.TotalItem = query.Count();
                query = query.Skip(((categoryFilterModel.PaginationModel.CurrentPage - 1) * categoryFilterModel.PaginationModel.PageSize)).Take(categoryFilterModel.PaginationModel.PageSize);
                announcementListAndPaginationModel.Announcements = query;
                announcementListAndPaginationModel.CategoryFilterModel = categoryFilterModel;
                return View(announcementListAndPaginationModel);
            }
            var queryWithCategoryId = (categoryFilterModel.IsIntern == true) ? announcementService.getAllStajyerAnnouncementByCategoryId((int)categoryFilterModel.CategoryId) : announcementService.getAllCompanyAnnouncementByCategoryId((int)categoryFilterModel.CategoryId);
            if (!string.IsNullOrEmpty(searchedWords))
            {
                queryWithCategoryId = queryWithCategoryId.Where(a => a.Explanation.ToLower().Contains(searchedWords) || a.Title.ToLower().Contains(searchedWords) || a.Name.ToLower().Contains(searchedWords));
            }
            announcementListAndPaginationModel.PaginationModel = categoryFilterModel.PaginationModel;
            announcementListAndPaginationModel.PaginationModel.TotalItem = queryWithCategoryId.Count();
            queryWithCategoryId = queryWithCategoryId.Skip(((categoryFilterModel.PaginationModel.CurrentPage - 1) * categoryFilterModel.PaginationModel.PageSize)).Take(categoryFilterModel.PaginationModel.PageSize);
            announcementListAndPaginationModel.Announcements = queryWithCategoryId;
            announcementListAndPaginationModel.CategoryFilterModel = categoryFilterModel;
            return View(announcementListAndPaginationModel);

        }
    }
}

StajBul.WebUI/ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StajBul.Service;
using StajBul.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StajBul.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private ICategoryService categoryService;

        public CategoryMenuViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public IViewComponentResult Invoke(CategoryFilterModel categoryFilterModel)
        {
            //ViewBag.isIntern = RouteData?.Values["isIntern"]; //bu calismaz cunku bizim default route icinde isIntern diye bir alan yok ama controller adi action adi veya id olsaydi ise yarardi.
            ViewBag.categoryId = categoryFilterModel.CategoryId;
            ViewBag.isIntern = categoryFilterModel.IsIntern;
            return View(categoryService.getAll());
        }
    }
}

StajBul.WebUI/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="about-section">
    <h1>stajimibul.com Hakkında</h1>
    <p>Öğrenciyken staj yeri bulmak bazen çok zor oluyor çünkü genelde ilan uygulamalarında mezun olmuş kişiler için ilanlar bulunuyor. Bunu kolaylaştırmak için sadece staj ilanlarının bulunduğu bir platform burası.Hem öğrenciler staj aradıklarını belirtmek için ilan oluşturabilirler hem stajyer arayan firmalar ilan oluşturabilirler.</p>
    <h1>İletişim</h1>
    <p><i class="fab fa-twitter mr-1"></i><a href="https://twitter.com/kutayyaman1">kutayyaman1</a></p>
    <p><i class="fas fa-envelope-square mr-1"></i>stajimibulinfo@gmail.com</p>
</div>

StajBul.WebUI/Views/Home/Details.cshtml
@model InternshipAnnouncement
@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="col-md-12">

            <div class="card text-center">
                <div class="card-header">
                    @Model.Name
                </div>
                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <small class="card-subtitle mb-2 text-muted">@Model.Category.CategoryName</small>
                    <p class="card-text">@Model.Explanation <br />@Model.Address?.City.CityName<br />@Model.Address?.District<br />@Model.Address?.AddressLine1<br />@Model.Address?.AddressLine2<br />@Model.Address?.PostalCode<br />@Model.Mail </p>
                    <a href='javascript:history.go(-1)' class="btn btn-primary">Geri Git</a>
                    <a class="btn btn-primary ml-2" href="/User/Profile?id=@Model.UserId">Kullanıcı Profilini Gör</a>
                </div>
                <div class="card-footer ">
                    @Model.CreatedDate
                </div>
            </div>
    </div>
</div>

StajBul.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@section SearchBar
{
    @Html.Partial("_SearchBar", (CategoryFilterModel)ViewBag.categoryFilterModel)
}
<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoryMenu", ViewBag.categoryFilterModel)
    </div>
    <div class="col-md-9">
        @await Component.InvokeAsync("AnnouncementList", ViewBag.categoryFilterModel)
    </div>
</div>