StajBul.WebUI/Models/ResetPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StajBul.WebUI.Models
{
    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name ="Şifreni Onayla")]
        [Compare("Password", ErrorMessage ="Şifre Eşleşmiyor")]
        public string ConfirmPassword { get; set; }

        public string Token { get; set; }

    }
}

StajBul.WebUI/Controllers/AnnouncementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmailService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StajBul.Data.Abstract;
using StajBul.Entity;
using StajBul.Service;

namespace StajBul.WebUI.Controllers
{
    public class AnnouncementController : Controller
    {
        private IAnnouncementService announcementService;
        private ICategoryService categoryService;
        private IAddressService addressService;
        private ICityService cityService;
        private UserManager<User> userManager;
        private readonly IEmailSender emailSender;
        public AnnouncementController(IAnnouncementService announcementService, ICategoryService categoryService, IAddressService addressService,ICityService cityService, UserManager<User> userManager,IEmailSender emailSender)
        {
            this.announcementService = announcementService;
            this.categoryService = categoryService;
            this.addressService = addressService;
            this.cityService = cityService;
            this.userManager = userManager;
            this.emailSender = emailSender;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult List()
        {
            IQueryable<InternshipAnnouncement> announcements = announcementService.getAll();
            return View(announcements);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.categories = new SelectList(categoryService.getAll(), "Id", "CategoryName"); //kullaniciya CategoryName'ler gozukcek ama hangisini sectiyse onun Id'si formdan arka tarafa gelcek.
            ViewBag.cities = new SelectList(cityService.getAll(), "Id", "CityName"); //kullaniciya CategoryName'ler gozukcek ama hangisini sectiyse onun Id'si formdan arka tarafa gelcek.
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(InternshipAnnouncement announcement)
        {
            var user = await userManager.FindByNameAsync(User?.Identity?.Name);
            announcement.UserId = user.Id;
            DateTime dateTime = DateTime.Now;
            string createdDate = dateTime.ToString();
            announcement.CreatedDate = createdDate;
            if (ModelState.IsValid)//Validasyonlar tamamsa demek oluyor yani validasyonlari ekledigim zaman anlamli olacak.
            {
                //announcement.Address.UserId = announcement.UserId; //Her adres bir user'a ait olcak diye bir sey yok bu ilanin adresi
                ///announcement.AddressId = addressService.getNextId(); //Bu sql serverda hata veriyor
                addressService.addAddress(announcement.Address);

                // announcement.Id = announcementService.getNextId();//Bu sql serverda hata veriyor
                announcementService.addInternshipAnnouncement(announcement);
                Category category = categoryService.getById(announcement.CategoryId);
                var message = new Message(new string[] { "yamankutay1@gmail.com" }, "Yeni İlan Eklendi","Kullanıcı Adı : " + announcement.User.UserName + "\nAdı : "+ user.UserRealName + "\nİlan Başlığı : " + announcement.Title + "\nİlan İçeriği : " + announcement.Explanation + "\nKategorisi : " + category.CategoryName + "\nİlan Tipi : " +announcement.AnnouncementType);
                emailSender.SendEmail(message);
                return RedirectToAction("Details","Home", new { id = announcement.Id });
            }

            ViewBag.categories = new SelectList(categoryService.getAll(), "Id", "CategoryName"); //kullaniciya CategoryName'ler gozukcek ama hangisini sectiyse onun Id'si formdan arka tarafa gelcek.
            return View(announcement);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            User user = await userManager.FindByNameAsync(User?.Identity?.Name);
            InternshipAnnouncement announcement = announcementService.getById(id);
            if(announcement == null)
            {
                return NotFound();
            }
            if (announcement.UserId != user.Id && !User.IsInRole("Admin"))
            {
                return NotFound();
            }
            else
            {
                ViewBag.categories = new SelectList(categoryService.getAll(), "Id", "CategoryName"); //kullaniciya CategoryName'ler gozukcek ama hangisini sectiyse onun Id'si formdan arka tarafa gelcek.
                ViewBag.cities = new SelectList(cityService.getAll(), "Id", "CityName");
                return View(announcementService.getById(id));
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> EditPost(InternshipAnnouncement announcement)
        {
            User user = await userManager.FindByNameAsync(User?.Identity?.Name);
            if (announcement.UserId != user.Id && !User.IsInRole("Admin"))
            {
                return NotFound();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    announcement.ModifiedDate = DateTime.Now.ToString();
                    announcementService.updateInternshipAnnouncement(announcement);
                    TempData["message"] = $"{announcement.Title} Güncellendi.";
                    return RedirectToAction("Index","Home");
                }

                ViewBag.categories = new SelectList(categoryService.getAll(), "Id", "CategoryName"); //kullaniciya CategoryName'ler gozukcek ama hangisini sectiyse onun Id'si formdan arka tarafa gelcek.
                ViewBag.cities = new SelectList(cityService.getAll(), "Id", "CityName");
                return View(announcement);
            }    
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            User user = await userManager.FindByNameAsync(User?.Identity?.Name);
            InternshipAnnouncement announcement = announcementService.getById(id);
            if (announcement.UserId != user.Id && !User.IsInRole("Admin"))
            {
                return NotFound();
            }
            return View(announcementService.getById(id));
        }

        [HttpPost, ActionName("Delete")]
        [Authorize]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            User user = await userManager.FindByNameAsync(User?.Identity?.Name);
            InternshipAnnouncement announcement = announcementService.getById(id);
            if (announcement.UserId != user.Id && !User.IsInRole("Admin"))
            {
                return NotFound();
            }
            announcementService.deleteInternshipAnnouncementById(id);
            TempData["message"] = id+ "id'li Kayıt Silindi.";
            return RedirectToAction("Index","Home");
        }

    }
}

StajBul.WebUI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmailService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using StajBul.Entity;
using StajBul.Service;
using StajBul.WebUI.Models;

namespace StajBul.WebUI.Controllers
{
    public class UserController : Controller
    {
        private IUserService userService;

        private UserManager<User> userManager;
        private IPasswordValidator<User> passwordValidator;
        private IPasswordHasher<User> passwordHasher;
        private IUserValidator<User> userValidator;
        private SignInManager<User> signInManager;
        private IAnnouncementService announcementService;
        private readonly IEmailSender emailSender;
        private readonly IStringLocalizer<UserController> localizer;

        public UserController(IUserService userService, UserManager<User> userManager, IPasswordValidator<User> passwordValidator, IPasswordHasher<User> passwordHasher, IUserValidator<User> userValidator, SignInManager<User> signInManager, IAnnouncementService announcementService, IEmailSender emailSender, IStringLocalizer<UserController> localizer)
        {
            this.userService = userService;
            this.userManager = userManager;
            this.passwordHasher = passwordHasher;
            this.passwordValidator = passwordValidator;
            this.userValidator = userValidator;
            this.signInManager = signInManager;
            this.announcementService = announcementService;
            this.emailSender = emailSender;
            this.localizer = localizer;
        }

        [Authorize]
        [Authorize(Roles = "Admin")]
        public IActionResult List()
        {
            return View(userManager.Users.Where(u => u.RowStatus == RowStatus.ACTIVE).OrderByDescending(u => u.Id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new RegisterModel() { });
        }

        [HttpPost]
        public async Task<IActionResult> Create(RegisterModel registerModel)
        {
            bool mailExists = userManager.Users.Any(u => u.Email == registerModel.Email);
            if (mailExists)
            {
                ModelState.AddModelError("", "Bu Mail Adresi İle Bir Hesap Bulunuyor.");
            }
            bool usernameExists = userManager.Users.Any(u => u.UserName == registerModel.UserName);
            if (usernameExists)
            {
                ModelState.AddModelError("", "Bu Kullanıcı Adı Kullanılıyor.");
            }
            if (ModelState.IsValid)
            {
                User user = new User();
                user.UserName = registerModel.UserName;
                user.UserSurname = registerModel.UserSurname;
                user.Age = registerModel.Age;
                user.Email = registerModel.Email;
                user.UserRealName = registerModel.UserRealName;
                user.CreatedDate = DateTime.Now.ToString();
                

                var result = await userManager.CreateAsync(user,registerModel.Password);

                if (result.Succeeded && ModelState.IsValid)
                {
                    TempData["message"] = $"{user.UserName} Kullanıcı Adıyla Üyelik Oluşturuldu.";
                    return View("Login");
                }

                else
                {
                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
                
            }

            return View(registerModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            User user = await userManager.FindByNameAsync(User?.Identity?.Name);
            if (id != user?.Id && !User.IsInRole("Admin"))
            {
                return NotFound();
            }
            return View(userService.getById(id));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> EditPost(string Id, string Password, string Email, int Age, string UserName)
        {

            var user = await userManager.FindByIdAsync(Id);
            if (Id != user?.Id.ToString() && !User.IsInRole("Admin"))
            {
                return NotFound();
            }
            if (user != null)
            {
                user.Email = Email;
                user.Age = Age;
                user.UserName = UserName;
                IdentityResult validPass = null;
                IdentityResult validUser = null;
                if (!string.IsNullOrEmpty(Password))
                {
                    validPass = await passwordValidator.ValidateAsync(userManager, user, Password);

                    if (validPass.Succeeded)
                    {
                        user.PasswordHash = passwordHasher.HashPassword(user, Password);
                    }
                    else
                    {
                        foreach(var error in validPass.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }

                validUser = await userValidator.ValidateAsync(userManager, user);

                if (!validUser.Succeeded)
                {
                    foreach (var error in validUser.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }

                if (validUser.Succeeded && ModelState.IsValid)
                {
                    var result = await userManager.UpdateAsync(user);
                    if(result.Succeeded)
                    {
                        TempData["message"] = $"{user.Email} Mail Adresli Kullanıcı Güncellendi.";
                        return RedirectToAction("List");
                    }
                }
            }
            else //User isnot available
            {
                ModelState.AddModelError("", "Kullanıcı Bulunamadı");
            }

            return View("Edit",user);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            User user = await userManager.FindByNameAsync(User?.Identity?.Name);
            if (id != user?.Id && !User.IsInRole("Admin"))
            {
                return NotFound();
            }
            return View(userService.getById(id));
        }

        [HttpPost, ActionName("Delete")]
        [Authorize]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            User user = await userManager.FindByNameAsync(User?.Identity?.Name);
            if (id != user?.Id && !User.IsInRole("Admin"))
            {
                return NotFound();
            }
            userService.deleteUserById(id);
            TempData["message"] = id + "id'li Kayıt Silindi.";
            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //ne ise yariyor arastir.
        public async Task<IActionResult> Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByNameAsync(model.UserName);
                if(user != null)
                {
                    await signInManager.SignOutAsync();
                    var result = await signInManager.PasswordSignInAsync(user, model.Password, false, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Geçersiz Kullanıcı Adı Veya Şifre");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Geçersiz Kullanıcı Adı Veya Şifre");
                }
                
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            TempData["message"] = "Başarıyla Çıkış Yaptınız.";
            return RedirectToAction("login");
        }

        [HttpGet]
        public async Task<IActionResult> Profile(string username ,string? id, int page = 1)
        {
            if (page <= 0)
            {
                page = 1;
            }
            AnnouncementListAndPaginationModel returnModel = new AnnouncementListAndPaginationModel();
            returnModel.CategoryFilterModel = new CategoryFilterModel();
            returnModel.CategoryFilterModel.id = id;
            returnModel.CategoryFilterModel.username = username;
            UserProfileViewModel model = new UserProfileViewModel();
            PaginationModel paginationModel = new PaginationModel();
            paginationModel.CurrentPage = page;
            paginationModel.PageSize = 8;
            returnModel.PaginationModel = paginationModel;
            if (string.IsNullOrEmpty(username))
            {
                if (!string.IsNullOrEmpty(id)) //username ile degilde id ile profile ulasmak istemis
                {
                    model.User = userService.getById(int.Parse(id));
                    if (model.User == null)
                        return NotFound();
                    var AnnouncementQueryable = announcementService.getByUserId(model.User.Id);
                    returnModel.PaginationModel.TotalItem = AnnouncementQueryable.Count();

StajBul.WebUI/Views/User/AddAboutMe.cshtml
@model User
@{
    ViewData["Title"] = "AddAboutMe";
}

<div class="container">
    <h1>Profilinizde Görünecek Olan Hakkında Kısmını Oluştur</h1>
    <hr />

    <form asp-controller="User" asp-action="AddAboutMePost" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="AboutMe">Hakkımda</label>
            <textarea rows="4" asp-for="AboutMe" class="form-control"></textarea>
        </div>
        <button type="submit" class="btn btn-primary btn-lg btn-block mb-3">Hakkımda Oluştur</button>
    </form>

</div>

StajBul.WebUI/Views/User/Completed.cshtml
@model User
@{
    ViewData["Title"] = "Completed";
}

<div class="bg-primary text-white m-1 p-1">
    <h2>Hoşgeldin @Model.UserName, Üyelik İşlemlerin Tamamlandı Artık İlan Verebilirsin.</h2>
</div>

StajBul.WebUI/Views/User/Create.cshtml
@model RegisterModel
@{
    ViewData["Title"] = "Create";
}

@section scripts{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script>
        $(function () {
            $("input.input-validation-error").closest("form-group").addClass("has-danger"); //inputlarda input-validation-error classina sahip en yakindaki elemanlardan form-group classina sahip olana has-danger classini ekle demis olduk yani validasyondan gecemeyenleri kirmizi yapacak.
        })
    </script>
}

<div class="container">
    <h1>@Localizer["SignUp"]</h1>
    <hr />

    <div class="text-danger" asp-validation-summary="All"></div>

    <form id="createForm" onmousedown="changed(this)" class="p-1 m-1" asp-controller="User" asp-action="Create" method="post">
        <div class="form-group">
            <label asp-for="UserRealName">@Html.LabelFor(model => model.UserRealName)</label>
            <input asp-for="UserRealName" class="form-control">
            <div><span class="text-danger" asp-validation-for="UserRealName"></span></div>
        </div>
        <div class="form-group">
            <label asp-for="UserSurname">@Html.LabelFor(model => model.UserSurname)</label>
            <input asp-for="UserSurname" class="form-control">
            <div><span class="text-danger" asp-validation-for="UserSurname"></span></div>
        </div>
        <div class="form-group">
            <label asp-for="UserName">@Html.LabelFor(model => model.UserName)</label>
            <input asp-for="UserName" class="form-control">
            <div><span class="text-danger" asp-validation-for="UserName"></span></div>
        </div>
        <div class="form-group">
            <label asp-for="Email">@Html.LabelFor(model => model.Email)</label>
            <input asp-for="Email" class="form-control">
            <div><span class="text-danger" asp-validation-for="Email"></span></div>
        </div>
        <div class="form-group">
            <label asp-for="Password">@Html.LabelFor(model => model.Password)</label>
            <input type="password" asp-for="Password" class="form-control">
            <div><span class="text-danger" asp-validation-for="Password"></span></div>
        </div>
        <div class="form-group">
            <label asp-for="Age">@Html.LabelFor(model => model.Age)</label>
            <input asp-for="Age" class="form-control">
            <div><span class="text-danger" asp-validation-for="Age"></span></div>
        </div>
        <button type="submit" id="createBtn" class="btn btn-primary btn-lg btn-block mb-3">@Localizer["SignUp"]</button>
    </form>

</div>

<script>
    var createBtn = document.getElementById("createBtn");
    createBtn.addEventListener("click", createBtnClicked);
    function createBtnClicked(element) {
        createBtn.hidden = true;
    }

    function changed(element) {
        if (createBtn.hidden === true) {
            createBtn.hidden = false;
        }

    }
</script>

StajBul.WebUI/Views/User/Delete.cshtml
@model User
@{
    ViewData["Title"] = "Delete";
}


<div class="text-info">ID </div> @Model.Id
<div class="text-info">Mail Adresi </div> @Model.Email
<div class="text-info">Name </div> @Model.UserName
<div class="text-info">Surname </div> @Model.UserSurname
<h4>
    Silmek İstiyor Musunuz?
</h4>
<form asp-controller="User" asp-action="Delete" method="post">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger btn-lg btn-block">Sil</button>
</form>

StajBul.WebUI/Views/User/Profile.cshtml
@model AnnouncementListAndPaginationModel
@{
    ViewData["Title"] = "Profile";
}
    <div class="container">
        <div class="main-body">
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="~/images/loginPage.png" alt="Admin" class="rounded-circle" width="150">
                                <div class="mt-3">
                                    <h4>@Model.UserProfileViewModel.User.UserName</h4>
                                    <p class="text-secondary mb-1">
                                        @if (Model.UserProfileViewModel.User.AboutMe != null)
                                        {
                                            @Model.UserProfileViewModel.User.AboutMe;
                                            if (User.Identity.Name == @Model.UserProfileViewModel.User.UserName)
                                            {
                                                <div class="float-none"><a class="btn btn-primary btn-sm" asp-controller="User" asp-action="EditAboutMe" asp-route-id="@Model.UserProfileViewModel.User.Id"><i class="fas fa-edit">Güncelle</i></a></div>
                                            }
                                        }
                                        else
                                        {
                                            if (User.Identity.Name == @Model.UserProfileViewModel.User.UserName)
                                            {
                                                <div class="float-none"><a class="btn btn-primary btn-sm" asp-controller="User" asp-action="AddAboutMe" asp-route-id="@Model.UserProfileViewModel.User.Id"><i class="fas fa-edit">Hakkımda Bilgiler Ekle</i></a></div>
                                            }
                                        }
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    @*<div class="card mt-3">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">Website</h6>
                            <span class="text-secondary">DATABASEDEN CEKILCEK</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">Github</h6>
                            <span class="text-secondary">DATABASEDEN CEKILCEK</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">Twitter</h6>
                            <span class="text-secondary">DATABASEDEN CEKILCEK</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">Instagram</h6>
                            <span class="text-secondary">DATABASEDEN CEKILCEK</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">Facebook</h6>
                            <span class="text-secondary">DATABASEDEN CEKILCEK</span>
                        </li>
                    </ul>
                </div>*@
                </div>
                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Adı Ve Soyadı</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    @Model.UserProfileViewModel.User.UserRealName @Model.UserProfileViewModel.User.UserSurname
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    @Model.UserProfileViewModel.User.Email
                                </div>
                            </div>
                            <hr>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Adres Bilgisi</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    @if (Model.UserProfileViewModel.User.Address != null)
                                    {
                                        @Model.UserProfileViewModel.User.Address.City.CityName <span> </span> @Model.UserProfileViewModel.User.Address.District <br /> @Model.UserProfileViewModel.User.Address.AddressLine1 <br /> @Model.UserProfileViewModel.User.Address.AddressLine2
                                        if (User.Identity.Name == @Model.UserProfileViewModel.User.UserName)
                                        {
                                            <div class="float-right"><a class="btn btn-primary btn-sm" asp-controller="Address" asp-action="Edit" asp-route-id="@Model.UserProfileViewModel.User.Address.Id"><i class="fas fa-edit">Güncelle</i></a></div>
                                        }
                                    }
                                    else
                                    {
                                        if (User.Identity.Name == @Model.UserProfileViewModel.User.UserName)
                                        {
                                            <div class="float-right"><a class="btn btn-primary btn-sm" asp-controller="Address" asp-action="Create"><i class="fas fa-edit">Adres Ekle</i></a></div>
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                    <span class="badge badge-pill badge-primary">@Model.UserProfileViewModel.User.UserName Kişisine Ait @Model.PaginationModel.TotalItem Adet İlan Bulundu</span>
                    <div class="row gutters-sm">
                        @if (Model.UserProfileViewModel.Announcements.Count > 0)
                        {
                            @foreach (var announcement in Model.UserProfileViewModel.Announcements)
                            {
                                <div class="col-sm-6 mb-3">
                                    <div class="card h-100">
                                        <div class="card-body">
                                            <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">@announcement.Title</i>@announcement.Name</h6>
                                            <small>@announcement.Category.CategoryName</small>
                                            <small>@announcement.Address.City.CityName</small>
                                            <small>@announcement.Address.Phone</small>
                                            <div class="mt-3">
                                                <p class="text-body font-size-sm">@announcement.Explanation</p>
                                            </div>
                                            <small>@announcement.CreatedDate</small>
                                            @if (User.Identity.Name == announcement.User.UserName)
                                            {
                                                <div class="float-right"><a class="btn btn-danger btn-sm" asp-controller="Announcement" asp-action="Delete" asp-route-id="@announcement.Id"><i class="fas fa-times">Sil</i></a></div>
                                                <div class="float-right"><a class="btn btn-primary btn-sm mr-2" asp-controller="Announcement" asp-action="Edit" asp-route-id="@announcement.Id"><i class="fas fa-edit">Güncelle</i></a></div>
                                            }
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                        else
                        {
                            <div class="alert alert-info"> Bu Sayfada İlan Bulunamadı. </div>
                        }

                    </div>
                    <div page-model="@Model" page-action="Profile"></div>
                </div>
            </div>
            
        </div>
    </div>